### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OGR-stack** [zfbx/zdiscord#101]
Arguments: 
  C:\Users\Administrator\Desktop\Server\FXServer.exe C:\Users\Administrator\Desktop\Server\cfx-server-data-master\resources\yarn\yarn_cli.js install --ignore-scripts --cache-folder C:\Users\Administrator\Desktop\Server\cfx-server-data-master\cache\yarn-cache --mutex file:C:\Users\Administrator\Desktop\Server\cfx-server-data-master\cache\yarn-mutex

PATH: 
  C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python311\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\npm

Yarn version: 
  1.22.5

Node version: 
  16.9.1

Platform: 
  win32 x64

Trace: 
  SyntaxError: Invalid value type 47:0 in C:\Users\Administrator\Desktop\Server\cfx-server-data-master\resources\zdiscord\yarn.lock
      at Parser.unexpected (C:\Users\Administrator\Desktop\Server\cfx-server-data-master\resources\yarn\yarn_cli.js:34610:11)
      at Parser.parse (C:\Users\Administrator\Desktop\Server\cfx-server-data-master\resources\yarn\yarn_cli.js:34736:16)
      at Parser.parse (C:\Users\Administrator\Desktop\Server\cfx-server-data-master\resources\yarn\yarn_cli.js:34713:28)
      at parse (C:\Users\Administrator\Desktop\Server\cfx-server-data-master\resources\yarn\yarn_cli.js:34811:21)
      at module.exports.exports.default (C:\Users\Administrator\Desktop\Server\cfx-server-data-master\resources\yarn\yarn_cli.js:34380:96)
      at C:\Users\Administrator\Desktop\Server\cfx-server-data-master\resources\yarn\yarn_cli.js:2874:63
      at Generator.next (<anonymous>)
      at step (C:\Users\Administrator\Desktop\Server\cfx-server-data-master\resources\yarn\yarn_cli.js:310:30)
      at C:\Users\Administrator\Desktop\Server\cfx-server-data-master\resources\yarn\yarn_cli.js:321:13

 citizen-server-impl] Running build tasks on resource zdiscord - it'll restart once completed.
[ citizen-server-impl] Couldn't start resource zdiscord.
[         script:yarn] [yarn]	yarn install v1.22.5
[         script:yarn] Error: [yarn]	error An unexpected error occurred: "Invalid value type 47:0 in C:\\Users\\Administrator\\Desktop\\Server\\cfx-server-data-master\\resources\\zdiscord\\yarn.lock".
[         script:yarn] [yarn]	info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\Administrator\\Desktop\\Server\\cfx-server-data-master\\resources\\zdiscord\\yarn-error.log".
[         script:yarn] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ citizen-server-impl] Building resource zdiscord failed.
[ citizen-server-impl] Error data: yarn failed!

**Comment by zfbx** [comment]
not sure exactly what to make of this but i'll just cover some basics. 
make sure your yarn is up to date from the [cfx default resources](https://github.com/citizenfx/cfx-server-data/tree/master/resources/%5Bsystem%5D/%5Bbuilders%5D/yarn) repo. pull a fresh copy of the yarn.lock from zdiscord and replace it and clear your server cache just in case I suppose.. then try again? 

worst case there's a workaround to skip yarn entirely on my discord pinned in the zdiscord-chat channel. here's a link to the zip <https://cdn.discordapp.com/attachments/862934532110024734/918724690363691038/yarn.zip>
you'd just copy this into the zdiscord directory and it should skip yarn entirely
