### ISSUE TITLE
qbcore latest update issue

### ISSUE THREAD

**Issue by RadhwaneDZ** [zfbx/zdiscord#13]
since the last update of the qbcore this function no longer used 

`TriggerEvent('QBCore:GetObject', (obj) => { QBCore = obj });`

so they are using this 
local QBCore = exports['qb-core']:GetCoreObject()

i tried to add it on app.js but notworking 
```
let QBCore;
TriggerEvent('QBCore:GetObject', (obj) => { QBCore = obj });
if (QBCore) console.log("QBCore found! Supported QB commands will be loaded.");
```

**Comment by zfbx** [comment]
replacing 
```js
TriggerEvent('QBCore:GetObject', (obj) => { QBCore = obj });
```
with
```js
QBCore = global.exports['qb-core'].GetCoreObject()
```
doesn't work?

**Comment by RadhwaneDZ** [comment]
its work thanks

**Comment by RadhwaneDZ** [comment]
if its possible to add !tp ID someplace
where ID = player ID 
where someplace  = coords 
this coords can be defined 
like pillboxgarage = vector3(222.41, -797.8, 30.83)

**Comment by zfbx** [comment]
OH sorry, didn't realize you asked a follow up question, yeah that's possible to do using one of the other scripts like qb-jail. if you want to give this a shot I haven't tested it:
qb-teleport.js:
```js
module.exports = {
    name: 'teleport',
    alias: 'tp',
    description: 'Teleports player to location',
    args: `[id] [location]`,
    role: "mod",
    run(discord, msg, args) {

        const teleportLocations = {
            "pillboxgarage": [ 22.41, -797.8, 30.83 ],
            "anotherlocation": [ 1004.37, -593.2, 40.24 ], // dunno where this goes lol
        }

        let id = args.shift();
        if (!id) return discord.createMessage(msg.channel.id, "You must provide an ID of a player.");
        id = Number(id);
        if (isNaN(id)) return discord.createMessage(msg.channel.id, "This ID seems invalid.");
        if (!GetPlayerName(id)) return discord.createMessage(msg.channel.id, "This ID seems invalid.");

        let location = args.shift();
        if (!location) return discord.createMessage(msg.channel.id, "No location specified");
        let location = teleportLocations[location.toLowerCase()] || false;
        if (!location) return discord.createMessage(msg.channel.id, "Invalid location");

        player = QBCore.Functions.GetPlayer(id);
        SetEntityCoords(GetPlayerPed(player.PlayerData.source), location[0], location[1], location[2])

        console.log(`[${msg.nickname}] teleported ${id} to ${location}.`);
        msg.addReaction('✅');
    },
};
```

**Comment by dagarabhi463** [comment]
Error: Error: Disallowed intents specified
[     script:zdiscord]     at Shard._onWSClose (C:\Users\Administrateur\Downloads\CerberusFramework\resources\zdiscord\libs\eris\lib\gateway\Shard.js:2133:23)
[     script:zdiscord]     at WebSocket.emit (events.js:210:5)
[     script:zdiscord]     at WebSocket.emitClose (C:\Users\Administrateur\Downloads\CerberusFramework\resources\zdiscord\libs\ws\lib\websocket.js:247:10)
[     script:zdiscord]     at TLSSocket.socketOnClose (C:\Users\Administrateur\Downloads\CerberusFramework\resources\zdiscord\libs\ws\lib\websocket.js:1102:15)
[     script:zdiscord]     at TLSSocket.emit (events.js:215:7)
[     script:zdiscord]     at net.js:658:12
[     script:zdiscord]     at TCP.done (_tls_wrap.js:481:7)
